const data = {
    Accesories : {
        Earings : require("./alpaca/accessories/earings.png"),
        Flower: require("./alpaca/accessories/flower.png"), 
        Glasses: require("./alpaca/accessories/glasses.png"),
        Headphones: require("./alpaca/accessories/headphone.png"),
        None: undefined,
    },
    Background: {
        "Blue 1": require("./alpaca/backgrounds/blue50.png"),
        "Blue 2": require("./alpaca/backgrounds/blue60.png"),
        "Blue 3": require("./alpaca/backgrounds/blue70.png"),
        "Dark Blue 1": require("./alpaca/backgrounds/darkblue30.png"),
        "Dark Blue 2": require("./alpaca/backgrounds/darkblue50.png"),
        "Dark Blue 3": require("./alpaca/backgrounds/darkblue70.png"),
        "Green 1": require("./alpaca/backgrounds/green50.png"),
        "Green 2": require("./alpaca/backgrounds/green60.png"),
        "Green 3": require("./alpaca/backgrounds/green70.png"),
        "Grey 1": require("./alpaca/backgrounds/grey40.png"),
        "Grey 2": require("./alpaca/backgrounds/grey70.png"),
        "Grey 3": require("./alpaca/backgrounds/grey80.png"),
        "Red 1": require("./alpaca/backgrounds/red50.png"),
        "Red 2": require("./alpaca/backgrounds/red60.png"),
        "Red 3": require("./alpaca/backgrounds/red70.png"),
        "Yellow 1": require("./alpaca/backgrounds/yellow50.png"),
        "Yellow 2": require("./alpaca/backgrounds/yellow60.png"),
        "Yellow 3": require("./alpaca/backgrounds/yellow70.png"),
    },
    Ears : {
        default : require("./alpaca/ears/default.png"),
        "tilt backwards": require("./alpaca/ears/tilt-backward.png"), 
        "tilt forward": require("./alpaca/ears/tilt-forward.png"),
    },
    Eyes : {
        angry : require("./alpaca/eyes/angry.png"),
        default: require("./alpaca/eyes/default.png"), 
        naughty: require("./alpaca/eyes/naughty.png"),
        panda: require("./alpaca/eyes/panda.png"),
        smart: require("./alpaca/eyes/smart.png"),
        star: require("./alpaca/eyes/star.png"),
    },
    Hair : {
        bang : require("./alpaca/hair/bang.png"),
        curls: require("./alpaca/hair/curls.png"), 
        default: require("./alpaca/hair/default.png"),
        elegant: require("./alpaca/hair/elegant.png"),
        fancy: require("./alpaca/hair/fancy.png"),
        short: require("./alpaca/hair/short.png"),
    },
    Leg : {
        "bubble tea" : require("./alpaca/leg/bubble-tea.png"),
        "cookie" : require("./alpaca/leg/cookie.png"),
        "default" : require("./alpaca/leg/default.png"),
        "game console" : require("./alpaca/leg/game-console.png"),
        "tilt backward" : require("./alpaca/leg/tilt-forward.png"),
    },
    Mouth : {
        astonished : require("./alpaca/mouth/astonished.png"),
        default : require("./alpaca/mouth/default.png"),
        eating : require("./alpaca/mouth/eating.png"),
        laugh : require("./alpaca/mouth/laugh.png"),
        tongue : require("./alpaca/mouth/tongue.png"),
    },
    Neck : {
        "bend backward" : require("./alpaca/neck/bend-backward.png"),
        "default" : require("./alpaca/neck/default.png"),
        "bend forward" : require("./alpaca/neck/bend-forward.png"),
        "thick" : require("./alpaca/neck/thick.png"),
    },
}

export default data